[profile.default]
src = "src"
out = "out"
libs = ["lib"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
chainlink-brownie-contracts = { git = "https://github.com/smartcontractkit/chainlink-brownie-contracts", tag = "0.6.1" }
